name: Build and Push Devcontainer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - devcontainer_path: ./src/large
            image_name: devcontainer-large

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}
          tags: |
            type=raw,value={{date 'YYYYMMDD'}},enable={{is_default_branch}}
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{ matrix.devcontainer_path }}
          imageName: ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}
          push: always
          platform: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
